config/routes.rb
Rails.application.routes.draw do
  get 'home/course_info'

  get 'home/course_details'

  devise_for :deviseusers
  get 'home/catalog_update'

  get 'test/test'

  get 'home/search'
  post 'home/search'
  get 'home/catalog'

  resources :usermails
  get 'welcome/signup'
  post 'welcome/signup'
  get 'welcome/login'
  post 'welcome/login'
  get 'welcome/index'
  post 'welcome/index'
  get 'welcome/index'
  root 'welcome#index'

  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/usermail.rb
class Usermail < ApplicationRecord
end

app/controllers/usermails_controller.rb
class UsermailsController < ApplicationController
  before_action :set_usermail, only: [:show, :edit, :update, :destroy]

  # GET /usermails
  # GET /usermails.json
  def index
    @usermails = Usermail.all
  end

  # GET /usermails/1
  # GET /usermails/1.json
  def show
  end

  # GET /usermails/new
  def new
    @usermail = Usermail.new
  end

  # GET /usermails/1/edit
  def edit
  end

  # POST /usermails
  # POST /usermails.json
  def create
    @usermail = Usermail.new(usermail_params)

    respond_to do |format|
      if @usermail.save
        format.html { redirect_to @usermail, notice: 'Usermail was successfully created.' }
        format.json { render :show, status: :created, location: @usermail }
      else
        format.html { render :new }
        format.json { render json: @usermail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usermails/1
  # PATCH/PUT /usermails/1.json
  def update
    respond_to do |format|
      if @usermail.update(usermail_params)
        format.html { redirect_to @usermail, notice: 'Usermail was successfully updated.' }
        format.json { render :show, status: :ok, location: @usermail }
      else
        format.html { render :edit }
        format.json { render json: @usermail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usermails/1
  # DELETE /usermails/1.json
  def destroy
    @usermail.destroy
    respond_to do |format|
      format.html { redirect_to usermails_url, notice: 'Usermail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usermail
      @usermail = Usermail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usermail_params
      params.require(:usermail).permit(:name, :email)
    end
end

app/helpers/usermails_helper.rb
module UsermailsHelper
end

app/views/usermails/_form.html.erb
<%= form_for(usermail) do |f| %>
  <% if usermail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usermail.errors.count, "error") %> prohibited this usermail from being saved:</h2>

      <ul>
      <% usermail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usermails/edit.html.erb
<h1>Editing Usermail</h1>

<%= render 'form', usermail: @usermail %>

<%= link_to 'Show', @usermail %> |
<%= link_to 'Back', usermails_path %>

app/views/usermails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usermails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usermails.each do |usermail| %>
      <tr>
        <td><%= usermail.name %></td>
        <td><%= usermail.email %></td>
        <td><%= link_to 'Show', usermail %></td>
        <td><%= link_to 'Edit', edit_usermail_path(usermail) %></td>
        <td><%= link_to 'Destroy', usermail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usermail', new_usermail_path %>

app/views/usermails/new.html.erb
<h1>New Usermail</h1>

<%= render 'form', usermail: @usermail %>

<%= link_to 'Back', usermails_path %>

app/views/usermails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @usermail.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usermail.email %>
</p>

<%= link_to 'Edit', edit_usermail_path(@usermail) %> |
<%= link_to 'Back', usermails_path %>